config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :options
  resources :profiles do
    get '/search', :to => 'profiles#search'
    get '/filter', :to => 'profiles#filter', on: :collection
  end
  root to: "home#index"
  

end

app/models/profile_type.rb
class ProfileType < ActiveRecord::Base
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
	def index
		
		if (params[:age_to].to_i < params[:age_from].to_i)
			redirect_to profile_search_path(current_user.id), :notice => "Invalid Age"
		else
			@user = User.joins(:address).where("users.id = addresses.id and addresses.country_id = ?
				and users.age >= ? and users.age <= ? and users.gender = ? and users.religion_id = ? 
				and users.mother_tongue_id = ? and addresses.state_id = ?", params[:country].to_i, params[:age_from].to_i,
				params[:age_to].to_i, params[:gender], params[:religion_id].to_i, params[:mt].to_i, params[:state].to_i)
			#respond_to :html, :json
		end
	end

	def new 
		@user = User.new
		@user.build_address
		@user.build_physicaldetail
		@user.build_userastro
		@user.build_user_qualification
		@user.build_user_partner
    end

	def edit
		@user = User.find(params[:id])
		@user.build_address if @user.address.nil?
		@user.build_physicaldetail if @user.physicaldetail.nil?
		@user.build_userastro if @user.userastro.nil?
		@user.build_user_qualification if @user.user_qualification.nil?
		@user.build_user_partner if @user.user_partner.nil?
	end

	def create
		@user = User.new(user_params)
		@user.save
	end

	def update
	#	redirect_to profile_edit
		@user = User.find(params[:id])
		#@address = Address.find(params[:id])	
		#user = user + 1;
		@user.build_physicaldetail if @user.physicaldetail.nil?
		@user.build_userastro if @user.userastro.nil?
		@user.build_user_qualification if @user.user_qualification.nil?
		@user.build_user_partner if @user.user_partner.nil?
		@user.update(user_params)
		@step = params[:step].to_s
		puts "#{@step}"*50

		if @step == "1"
			render "profiles/_step2"
		elsif @step == "2"
			render "profiles/_step3"
			#redirect_to :controller=>'profiles', :action => 'edit'
			#redirect_to profile_edit1_path(current_user.id)
		elsif @step == "3"
			render "profiles/_step4"
		elsif @step == "4"
			redirect_to :controller=>'options', :action => 'index'
		else
			render "edit"
		end
    end

    def filter
    	exec_qry = ""
    		if params[:religion].present?
    			exec_qry = exec_qry + " and " + religion_param
    		end

    		if params[:caste].present?
    			exec_qry = exec_qry + " and " + caste_param
    		end

    		if params[:mt].present?
    			exec_qry = exec_qry + " and " + mt_param
    		end

    		if params[:country].present?
    			exec_qry = exec_qry + " and " + country_param
    		end

    		if params[:state].present?
    			exec_qry = exec_qry + " and " + state_param
    		end

    		if params[:edu_level].present?
    			exec_qry = exec_qry + " and " + edu_level_param
    		end

    		if params[:work_with].present?
    			exec_qry = exec_qry + " and " + work_with_param
    		end

    		if params[:profession].present?
    			exec_qry = exec_qry + " and " + profession_param
    		end

    		if params[:income].present?
    			exec_qry = exec_qry + " and " + income_param
    		end	
    		@user = User.joins(:address, :user_qualification).where("users.id = addresses.id and 
    					users.id = user_qualifications.user_id" + exec_qry)
    		render :json => @user
	end

    def search 
    	@user = User.joins(:address).where("users.id = addresses.id and addresses.country_id = ?
				and users.age >= ? and users.age <= ? and users.gender = ? and users.religion_id = ? 
				and users.mother_tongue_id = ? and addresses.state_id = ?", params[:country].to_i, params[:age_from].to_i,
				params[:age_to].to_i, params[:gender], params[:religion_id].to_i, params[:mt].to_i, params[:state].to_i)
    	#@user_search = User.search(params[:age_from], params[:age_to], params[:gender], params[:religion_id], params[:mt],
    		#params[:country_id], params[:state_id])
    end

    def show
    	
    end

    def religion_param
    		religion ="("
    	params[:religion].each do |i|
    		if i == params[:religion].last
    			religion = religion + "users.religion_id = " + i + ")"
    		else
				religion = religion + "users.religion_id = " + i + " or "
			end
    	end
    	return religion
    end

    def caste_param
    		caste ="("
    	params[:caste].each do |i|
    		if i == params[:caste].last
    			caste = caste + "users.caste_id = " + i + ")"
    		else
				caste = caste + "users.caste_id = " + i + " or "
			end
    	end
    	return caste
    end

    def mt_param
    		mt ="("
    	params[:mt].each do |i|
    		if i == params[:mt].last
    			mt = mt + "users.mother_tongue_id = " + i + ")"
    		else
				mt = mt + "users.mother_tongue_id = " + i + " or "
			end
    	end
    	return mt
    end

    def country_param
    		country ="("
    	params[:country].each do |i|
    		if i == params[:country].last
    			country = country + "addresses.country_id = " + i + ")"
    		else
				country = country + "addresses.country_id = " + i + " or "
			end
    	end
    	return country
    end

    def state_param
    		state ="("
    	params[:state].each do |i|
    		if i == params[:state].last
    			state = state + "addresses.state_id = " + i + ")"
    		else
				state = state + "addresses.state_id = " + i + " or "
			end
    	end
    	return state
    end

	def edu_level_param
    		edu_level ="("
    	params[:edu_level].each do |i|
    		if i == params[:edu_level].last
    			edu_level = edu_level + "user_qualifications.education_level_id = " + i + ")"
    		else
				edu_level = edu_level + "user_qualifications.education_level_id = " + i + " or "
			end
    	end
    	return edu_level
    end

    def profession_param
    		profession ="("
    	params[:profession].each do |i|
    		if i == params[:profession].last
    			profession = profession + "user_qualifications.occupation_id = " + i + ")"
    		else
				profession = profession + "user_qualifications.occupation_id = " + i + " or "
			end
    	end
    	return profession
    end

    def work_with_param
    		work_with ="("
    	params[:work_with].each do |i|
    		if i == params[:work_with].last
    			work_with = work_with + "user_qualifications.working_with = " + i + ")"
    		else
				work_with = work_with + "user_qualifications.working_with = " + i + " or "
			end
    	end
    	return work_with
    end

    def income_param
    		income ="("
    	params[:income].each do |i|
    		if i == params[:income].last
    			income = income + "user_qualifications.annual_income_id = " + i + ")"
    		else
				income = income + "user_qualifications.annual_income_id = " + i + " or "
			end
    	end
    	return income
    end    
end

private 
	def user_params
		params.require(:user).permit(:user_name, :date_of_birth, :age, :phone_no, :gender,
		 :religion_id, :caste_id, :mother_tongue_id, 
		 address_attributes: [:id, :country_id, :state_id, :city_id, :user_id], 
		 physicaldetail_attributes: [:id, :height, :weight, :body_type, :user_id, :skin_tone, :hair_color, :eye_color, :physical_status, :health_condition],
		 userastro_attributes: [:id, :user_id, :rasi_id, :nakshatra_id, :gothram_id],
		 user_qualification_attributes: [:id, :user_id, :education_id, :education_field_id, :education_level_id, :working_with, :annual_income_id, :occupation_id],
		 user_partner_attributes: [:id, :user_id, :age, :height, :marital_status_id, :religion_id, :caste_id, :gothram_id, :mother_tongue_id])
	end

	

app/helpers/profile_helper.rb
module ProfileHelper
end

app/views/profiles/_step1.html.erb
<%= form_for @user, :url => {:action => "update"} do |f| %>
<%= hidden_field_tag :step, "1" %>
	<table>
		<tr> <td colspan="2"> <%= current_user.email %></td></tr>
		<tr>
			<td> <%= f.label :Name %> </td>
			<td> <%= f.text_field :user_name, :required => true %></td>
		</tr>

		<tr>
			<td> <%= f.label :Gender %> </td>
			<td> <%= f.radio_button(:gender, "male") %>
				<%= f.label(:gender_male, "Male") %>
				<%= f.radio_button(:gender, "female") %>
				<%= f.label(:gender_female, "Female") %>
			</td>
		</tr>
		
		<tr>
			<td> <%= f.label :Date_Of_Birth %></td>
			<td> <%= f.text_field :date_of_birth, :required => true %>
			</td>
		</tr>

		<tr>
			<td> <%= f.label :Age %></td>
			<td> <%= f.text_field :age, :required => true %></td>
		</tr>

		<tr>
			<td> <%= f.label :Mobile_Number %></td>
			<td> <%= f.text_field :phone_no, :required => true %></td>
		</tr>

		<tr>
			<td> <%= f.label :Religion %></td>
			<td> <%= f.select(:religion_id, options_from_collection_for_select(Religion.all, 'id', 'rel_name', f.object.religion_id)) %>
			</td>
		</tr>

		<tr>
			<td> <%= f.label :Caste %></td>
			<td> <%= f.select(:caste_id, options_from_collection_for_select(Caste.all, 'id', 'caste_name', f.object.caste_id)) %>
				
			</td>
		</tr>

		<tr>
			<td> <%= f.label :Mother_tongue %></td>
			<td> <%= f.select(:mother_tongue_id, options_from_collection_for_select(Language.all, 'id', 'lang_name', f.object.mother_tongue_id)) %>
				
			</td>
		</tr>

		<%= f.fields_for :address do |add| %>
			<tr>
				<td> <%= add.label :Country_Living_in %></td>
				<td> <%= add.select(:country_id, options_from_collection_for_select(Country.all, 'id', 'country_name', add.object.country_id)) %>
				
				</td>
			</tr>

			<tr>
				<td> <%= add.label :State_Living_in %></td>
				<td> <%= add.select(:state_id, options_from_collection_for_select(State.all, 'id', 'state_name', add.object.state_id)) %>
				
				</td>
			</tr>

			<tr>
				<td> <%= add.label :City_Living_in %></td>
				<td> <%= add.select(:city_id, options_from_collection_for_select(City.all, 'id', 'city_name', add.object.city_id)) %>
				
				</td>
			</tr>
		<% end %>
	</table>
<%= f.submit :"Continue" %>
<% end %>

app/views/profiles/_step2.html.erb
<%= link_to "HOME", options_path %>
<h1>Edit Profile</h1>
<%= form_for @user, :url => {:action => "update"} do |f| %>


<%= hidden_field_tag :step, "2" %>
	<table>
		<tr> <td colspan="2"> <%= current_user.email %></td></tr>
		<%= f.fields_for :physicaldetail do |phy| %>
		
			<tr>
				<td> <%= phy.label :Height %> </td>
				<td> <%= phy.text_field :height, :required => true %></td>
			</tr>

			<tr>
				<td> <%= phy.label :Weight %> </td>
				<td> <%= phy.text_field :weight, :required => true %></td>
			</tr>

			<tr>
				<td> <%= phy.label :Skin_tone %> </td>
				<td> <%= phy.radio_button(:skin_tone, "Very Fair") %>
					<%= phy.label(:skin_tone_veryfair, "Very Fair") %>
				 	<%= phy.radio_button(:skin_tone, "Fair") %>
					<%= phy.label(:skin_tone_fair, "Fair") %>
				 	<%= phy.radio_button(:skin_tone, "Wheatish") %>
					<%= phy.label(:skin_tone_wheatish, "Wheatish") %>
				 	<%= phy.radio_button(:skin_tone, "Dark") %>
					<%= phy.label(:skin_tone_dark, "Dark") %>
				</td>
			</tr>

			<tr>
				<td> <%= phy.label :Body_Type %> </td>
				<td> <%= phy.radio_button(:body_type, "Slim") %>
					<%= phy.label(:body_type_slim, "Slim") %>
					<%= phy.radio_button(:body_type, "Athletic") %>
					<%= phy.label(:body_type_athletic, "Athletic") %>
					<%= phy.radio_button(:body_type, "Average") %>
					<%= phy.label(:body_type_average, "Average") %>
					<%= phy.radio_button(:body_type, "Heavy") %>
					<%= phy.label(:body_type_heavy, "Heavy") %>	
				</td>
			</tr>

			<tr>
				<td> <%= phy.label :Hair_Color %> </td>
				<td> <%= phy.radio_button(:hair_color, "Brownish") %>
					<%= phy.label(:hair_color_brownish, "Brownish") %>
					<%= phy.radio_button(:hair_color, "Whitish") %>
					<%= phy.label(:hair_color_whitish, "Whitish") %>
					<%= phy.radio_button(:hair_color, "Black") %>
					<%= phy.label(:hair_color_whitish, "Black") %>
				</td>
			</tr>

			<tr>
				<td> <%= phy.label :Eye_Color %> </td>
				<td> <%= phy.radio_button(:eye_color, "Normal") %>
					<%= phy.label(:eye_color_normal, "Normal") %>
					<%= phy.radio_button(:eye_color, "Blue") %>
					<%= phy.label(:eye_color_whitish, "Blue") %> 
					<%= phy.radio_button(:eye_color, "Brownish") %>
					<%= phy.label(:eye_color_brownish, "Brownish") %>
				</td>
			</tr>

			<tr>
				<td> <%= phy.label :Physical_Status %> </td>
				<td> <%= phy.radio_button(:physical_status, "Normal") %>
					<%= phy.label(:physical_status_normal, "Normal") %>
					<%= phy.radio_button(:physical_status, "Physically Challenged") %>
					<%= phy.label(:physical_status_chalanged, "Physically Challenged") %> 
				</td>
			</tr>

			<tr>
				<td> <%= phy.label :Health_Condition %> </td>
				<td> <%= phy.radio_button(:health_condition, "Normal") %>
					<%= phy.label(:health_condition_np, "Normal") %>
					<%= phy.radio_button(:health_condition, "Low BP") %>
					<%= phy.label(:health_condition, "Low BP") %> 
					<%= phy.radio_button(:health_condition, "High BP") %>
					<%= phy.label(:health_condition, "High BP") %> 
					<%= phy.radio_button(:health_condition, "Heart Ailments") %>
					<%= phy.label(:health_condition, "Heart Ailments") %>
					<%= phy.radio_button(:health_condition, "Diabetes") %>
					<%= phy.label(:health_condition, "Diabetes") %>
					<%= phy.radio_button(:health_condition, "HIV Positive") %>
					<%= phy.label(:health_condition, "HIV Positive") %>
				</td>
			</tr>
		
		<% end %>
		<tr><td><%= f.submit :"Continue" %></td></tr>
	</table>	
<% end %>

app/views/profiles/_step3.html.erb
<%= link_to "HOME", options_path %>
<h1>Edit Profile</h1>
<%= form_for @user, :url => {:action => "update"} do |f| %>

<%= hidden_field_tag :step, "3" %>
<table>
		<tr> <td colspan="2"> <%= current_user.email %></td></tr>
		<%= f.fields_for :userastro do |a| %>
		
			<tr>
				<td> <%= a.label :Gothram %> </td>
				<td> <%= a.select(:gothram_id, options_from_collection_for_select(Gothram.all, 'id', 'gothram_name', a.object.gothram_id)) %>
			</tr>

			<tr>
				<td> <%= a.label :Nakshatram %> </td>
				<td> <%= a.select(:nakshatra_id, options_from_collection_for_select(Nakshatra.all, 'id', 'nakshatra_name', a.object.nakshatra_id)) %>
			</tr>

			<tr>
				<td> <%= a.label :Rasi %> </td>
				<td> <%= a.select(:rasi_id, options_from_collection_for_select(Rasi.all, 'id', 'rasi_name', a.object.rasi_id)) %>
			</tr>
		<% end %>
		<tr><td colspan="2"><h4>Education/Career Details</h4></td></tr>
		<%= f.fields_for :user_qualification do |q| %>
		
			<tr>
				<td> <%= q.label :Education_Level %> </td>
				<td> <%= q.select(:education_level_id, options_from_collection_for_select(EducationLevel.all, 'id', 'level_name', q.object.education_level_id)) %>
				</td>
			</tr>

			<tr>
				<td> <%= q.label :Education_Field %> </td>
				<td> <%= q.select(:education_field_id, options_from_collection_for_select(EducationField.all, 'id', 'field_name', q.object.education_field_id)) %>
				</td>
			</tr>

			<tr>
				<td> <%= q.label :Course_Name %> </td>
				<td> <%= q.select(:education_id, options_from_collection_for_select(Education.all, 'id', 'course_name', q.object.education_id)) %>
				</td>
			</tr>

			<tr>
				<td> <%= q.label :Working_With %> </td>
				<td> <%= q.radio_button(:working_with, "Private Company") %>
					<%= q.label(:working_with, "Private Company") %>
				 	<%= q.radio_button(:working_with, "MNC") %>
					<%= q.label(:working_with, "MNC") %>
					<%= q.radio_button(:working_with, "Government") %>
					<%= q.label(:working_with, "Government") %>
				</td>
			</tr>

			<tr>
				<td> <%= q.label :Woring_As %> </td>
				<td> <%= q.select(:occupation_id, options_from_collection_for_select(Occupation.all, 'id', 'occ_name', q.object.occupation_id)) %>
				</td>
			</tr>

			<tr>
				<td> <%= q.label :Annual_Income %> </td>
				<td> <%= q.select(:annual_income_id, options_from_collection_for_select(AnnualIncome.all, 'id', 'income_type', q.object.annual_income_id)) %>
				</td>
			</tr>
		<% end %>

		<tr><td><%= f.submit :"Continue" %></td></tr>
</table>

<% end %>

app/views/profiles/edit.html.erb
<%= link_to "HOME", options_path %>
<h1>Edit Profile</h1>
<%= csrf_meta_tags %>
<%= form_for @user, :url => {:action => "update"} do |f| %>
	<%= render 'step1' %>

	
<% end %>

app/views/profiles/index.html.erb
<%= link_to "BACK", profile_search_path(current_user.id) %>
<%= link_to "HOME", options_path %>
<script type="text/javascript">
  $(function(){
  	$(document).on('change', function(){
  		var rel_val = new Array();
  		var caste_val = new Array();
  		var mt_val = new Array();
  		var country_val = new Array();
  		var state_val = new Array();
  		var edu_level_val = new Array();
  		var occ_val = new Array();
  		var work_with_val = new Array();
  		var income = new Array();

  		$.each($("input[name = 'religion']:checked"), function(i){
  			rel_val[i] = $(this).val();
  		});
  		
  		$.each($("input[name = 'caste']:checked"), function(i){
  			caste_val[i] = $(this).val();
  		});

  		$.each($("input[name = 'mt']:checked"), function(i){
  			mt_val[i] = $(this).val();
  		});

  		$.each($("input[name = 'country']:checked"), function(i){
  			country_val[i] = $(this).val();
  		});

  		$.each($("input[name = 'state']:checked"), function(i){
  			state_val[i] = $(this).val();
  		});

  		$.each($("input[name = 'edu_level']:checked"), function(i){
  			edu_level_val[i] = $(this).val();
  		});

  		$.each($("input[name = 'work_with']:checked"), function(i){
  			work_with_val[i] = $(this).val();
  		});

  		$.each($("input[name = 'profession']:checked"), function(i){
  			occ_val[i] = $(this).val();
  		});

  		$.each($("input[name = 'income']:checked"), function(i){
  			income[i] = $(this).val();
  		});

		
		$.ajax({
			url: '/profiles/filter',
    		type:'GET', 
    		
  			data: {religion: rel_val, caste: caste_val, mt: mt_val, country: country_val, state: state_val, edu_level: edu_level_val, profession: occ_val, work_with: work_with_val, income: income},
  			success: function (data) {
  				$('#result').html(data);
  				if(data[0] == null){
  					var row1 = "<tr><td><h3> No results found... </h3></td></tr>";
  					$('#result').append(row1);
  				};
  				
          		$.each(data, function(i){
          			
          			var row1 = "<tr><td><b>Name </b></td><td> : " + data[i].user_name + "</td></tr>";
  					var row2 = "<tr><td><b>Age </b></td><td> : " + data[i].age + "</td></tr>";
  					var row3 = "<tr><td><b>Date Of Birth </b></td><td> : " + data[i].date_of_birth + "</td></tr>";
  					var row4 = "<tr><td><b>Email </b><br><br></td><td> : " + data[i].email + "<br><br></td></tr>";
  					$('#result').append(row1);
  					$('#result').append(row2);
  					$('#result').append(row3);
  					$('#result').append(row4);
  				
          		});
  			},
  			error: function(data){
				alert("Error")
			}
  		});

		
		
  	});
  });
</script>

<h1>Matches</h1>

<table>
	<tr>
		<td><div style="height: 1000px; width: 330px; border: 1px solid black">
		<center><h3 style="background:#D8D8D8">Search Filters</h3></center>
		
	<table width="80%">
		<tr> 
			<td><b> <%= label_tag :Religion %></b></td>
		</tr>
		<tr>
			<td> <%= check_box_tag 'religion', '1' %> Hindu <br>
				 <%= check_box_tag 'religion', '2' %> Chiristian <br>
				 <%= check_box_tag 'religion', '3' %> Muslim <br><br>
			</td>
		</tr>

		<tr> 
			<td><b> <%= label_tag :Caste %></b></td>
		</tr>
		<tr>
			<td> <%= check_box_tag 'caste', '1' %> Nadar <br>
				 <%= check_box_tag 'caste', '2' %> Devar <br>
				 <%= check_box_tag 'caste', '3' %> Iyar <br><br>
			</td>
		</tr>

		<tr> 
			<td><b> <%= label_tag :Mother_Tongue %></b></td>
		</tr>
		<tr>
			<td> <%= check_box_tag 'mt', '1' %> Tamil <br>
				 <%= check_box_tag 'mt', '2' %> English <br>
				 <%= check_box_tag 'mt', '3' %> Hindi <br><br>
			</td>
		</tr>

		<tr> 
			<td><b> <%= label_tag :Country_Living_In %></b></td>
		</tr>
		<tr>
			<td> <%= check_box_tag 'country', '1' %> India <br>
				 <%= check_box_tag 'country', '2' %> US <br><br>
			</td>
		</tr>

		<tr> 
			<td><b> <%= label_tag :State_Living_In %></b></td>
		</tr>
		<tr>
			<td> <%= check_box_tag 'state', '1' %> Tamil Nadu <br>
				 <%= check_box_tag 'state', '2' %> Andhra <br><br>
			</td>
		</tr>

		<tr> 
			<td><b> <%= label_tag :Education_Level %></b></td>
		</tr>
		<tr>
			<td> <%= check_box_tag 'edu_level', '1' %> Master <br>
				 <%= check_box_tag 'edu_level', '2' %> Bachelor <br>
				 <%= check_box_tag 'edu_level', '3' %> Diploma <br><br>
			</td>
		</tr>

		<tr> 
			<td><b> <%= label_tag :Working_with %></b></td>
		</tr>
		<tr>
			<td> <%= check_box_tag 'work_with', '"Private Company"' %> Private Company <br>
				 <%= check_box_tag 'work_with', '"MNC"' %> MNC <br>
				 <%= check_box_tag 'work_with', '"Government"' %> Government/Public Sector <br><br>
			</td>
		</tr>

		<tr> 
			<td><b> <%= label_tag :Profession_Area %></b></td>
		</tr>
		<tr>
			<td> <%= check_box_tag 'profession', '1' %> Software Engineer <br>
				 <%= check_box_tag 'profession', '2' %> Electrician <br><br>
			</td>
		</tr>

		<tr> 
			<td><b> <%= label_tag :Annual_Income %></b></td>
		</tr>
		<tr>
			<td> <%= check_box_tag 'income', '1' %> 50,000 - 1,00,000 <br>
				 <%= check_box_tag 'income', '2' %> 1,00,000 - 2,00,000 <br>
				 <%= check_box_tag 'income', '3' %> 2,00,000 - 3,00,000 <br><br>
			</td>
		</tr>
	</table>

			
	</div></td>
	<td><div style="height: 1000px; width: 900px; border: 1px solid black">
		
		<center><h3 style="background:#D8D8D8">Search Results</h3>
		<table id = "result">
		
			<% if (@user.empty?) %>
				<tr><td><h3>No results found...</h3></td>
				</tr>
			<% else %>
			
			<% @user.each do |result| %>
				<tr>
					<td><b>Name</b></td> 
					<td> : <%= result.user_name %></td>
				</tr>
				<tr>
					<td><b>Age</b></td>
					<td> : <%= result.age %></td>
				</tr>
				<tr>
					<td><b>Date Of Birth</b></td>
					<td> : <%= result.date_of_birth %></td>
				</tr>
			
				<tr>
					<td><b>Email</b><br><br></td>
					<td> : <%= result.email %>
						&nbsp &nbsp <b>Phone No</b> : <%= result.phone_no %><br><br>
					</td>
				</tr>
			<% end %>
			<% end %>
		</table>
		</center>
			
		</div></td>
	</tr>
</table>

app/views/profiles/search.html.erb
<%= link_to "HOME", options_path %>
<h1>Simple Search</h1>
<%= form_tag profiles_path, :method => 'get' do %> 
	<table>
		<tr>
			<td colspan="3"> <%= label_tag :Looking_for %> 
			    <%= radio_button_tag :gender, 'male' %>
				<%= label_tag :Groom %>
				<%= radio_button_tag :gender, 'female' %>
				<%= label_tag :Bride %>
			</td>
		</tr>
		<tr>
			<td> <%= label_tag :Age_from %> <%= text_field_tag :age_from, params[:age_from] %> </td>
			<td> <%= label_tag :To %> <%= text_field_tag :age_to, params[:age_to] %> </td>
			<td> <%= submit_tag "Search", :name => nil %> </td>
		</tr>
	</table>
<% end %>

app/views/profiles/show.html.erb
<h1>Profiles</h1>
<table>
	<% @user.each do |result| %>
		<tr><td>Name :
			<%= result.user_name %></td>
			<td>Age : <%= result.age %>
				Email : <%= result.email %>
			</td>
		</tr>
	<% end %>
		
</table>